### ISSUE TITLE
Adding Receiver - Initialization of YNCA receiver RX-477 failed

### ISSUE THREAD

**Issue by peetersit** [mvdwetering/yamaha_ynca#106]
Hi,
@mvdwetering

I've succesfully added RX-473, RX-475

The RX-477 is added but fails to initialize and keeps restarting in initializing.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/121575883/210277242-727f2289-f714-47d2-be6d-420d2b6cb232.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/121575883/210277660-b5d2655c-a5e2-436f-80ac-5e3cdaac3899.png">

[home-assistant_yamaha_ynca_2023-01-02T20-52-21.151Z.log](https://github.com/mvdwetering/yamaha_ynca/files/10333460/home-assistant_yamaha_ynca_2023-01-02T20-52-21.151Z.log)

**Comment by mvdwetering** [comment]
Adding the log from the post in the other thread for reference as it also contains interesting info.
[home-assistant_yamaha_ynca_2023-01-02T19-55-41.700Z.log](https://github.com/mvdwetering/yamaha_ynca/files/10335407/home-assistant_yamaha_ynca_2023-01-02T19-55-41.700Z.log)

Hmm, the response from your receiver on the INITVOLLVL command  is a bit different from from mine. While I have improved parsing to at least continue on those cases it looks I missed a spot.

I will get that fixed for upcoming release. Hopefully somewhere around the upcoming weekend.

**Comment by peetersit** [comment]
Great, Thanks, no hurries, let met know if i need to test. thanks....

Not a bug, and as a novice, i don't seem to find anywhere how to sent a on/off/standby request to the receiver ("sent: @MAIN:PWR=Standby") trying to make a flow in node-red

**Comment by peetersit** [comment]
Hi, @mvdwetering, Any news yet? And i still have the question how to sent command to receiver to turn it on and off (standby mode)

**Comment by mvdwetering** [comment]
Great timing as I just finished the release :) 
It is still marked as a prerelease as I like to run it for a day or so myself before fully releaseing it. Even though I have a lot of tests sometimes things get missed. Will make it available as a normal release probably tomorrow or the day after.

>And i still have the question how to sent command to receiver to turn it on and off (standby mode)

Ow sorry, I missed that. The integration adds a service to Home Assistant for that.
You can play with the service through the Home Assistant developer tools, just search for YNCA in the sevices list.

For your example you call it like this:
```
service: yamaha_ynca.send_raw_ynca
data:
  raw_data: "@MAIN:PWR=Standby"
target:
  entity_id: media_player.main
```
I don't know if you can call that from node-red.

**Comment by mvdwetering** [comment]
I made the release available it should show up in HACS on next update.

**Comment by peetersit** [comment]
Great work! Tested 6.0, it worked right away……now to figure out how to sent commands to the receivers. Again good effort!
