### ISSUE TITLE
implementaion of menu cursor buttons

### ISSUE THREAD

**Issue by perfectfe** [mvdwetering/yamaha_ynca#121]
Is it possible to browse through the device menu using the left-right-up-down arrows?
according to this it should work: https://www.home-assistant.io/integrations/yamaha
but I had no chance to get it done.

are you able to integrate those controls to YNCA?

my final goal would be to execute a script that powers on my Yamaha, switches to SERVER and then starts a stream from a DNLA server,

I'm using a RX-V675.

Thanks for reading :-)

**Comment by mvdwetering** [comment]
There seem to be 2 ways to do this. 

It is possible to get info about the list that is on the screen and then select items, go to other pages etc... However that seems quite complicated and I don't know how I would expose that in Home Assistant in a good way. It should probably be through the Media Browser, but I don't think it supports paginated info.

The other way would be to send remotecodes. This seems easier, only thing is that I don't know how standard these codes are.

I found this repo which lists some codes https://github.com/BirdAPI/yamaha-network-receivers
I tried the ones for Up and Down and they work for me. 

Could you try them for your receiver?
To send the commands to the following:
* In Home Assistant open the Developer Tools
* Select the Services tab
* Select the "Send raw YNCA command" service
* Select your receiver entity or device
* Put the following in the data box `@SYS:REMOTECODE=7A859C63`
* Press "Call Service" (make sure there is something on screen so you can see if Down actually works)

You could try some more codes from the linked repo

When those codes work I could create a remote entity for it in Home Assistant that makes it easier to send those codes.

**Comment by perfectfe** [comment]
wow.

the codes work for my receiver, at least the cursor ones. if there's a need to test the other ones, please let me know.

with the information you provided, I could create an automation script which turns on the device and browses through my DLNA servers and their contents using arrow and enter keys. it's a static thing and works only as expected as long as I don't change anything on my contents. but for automatically starting my favorite radio station's stream it's perfectly fine for me.

i am already overjoyed with this solution and therefore do not need any dedicated entities for it. if you implement it anyway i would of course be happy to test it.

thank you so much!!

**Comment by mvdwetering** [comment]
Cool to hear it works for you. No need to test more from my side.

Since you already can buid what you needed I will just put adding dedicated Remote entities for this on the todo list. I will probably need it in a few months when I go automating a new remote.

**Comment by mvdwetering** [comment]
FYI it took a while, but since 7.5.0 release there is a remote entity which can send commands like  up, down, left, right. It also supports plain remote codes as provided to the REMOTECODE ynca command.

Check the section about the remote entity in the README for more info.

If your current solution is working fine for you there is no real reason to switch as all the remote entity does is translate the commands. Only thing you would really gain is that using command names is a bit more readable than codes.
