### ISSUE TITLE
Support for RX-V677?

### ISSUE THREAD

**Issue by YAMLcase** [mvdwetering/yamaha_ynca#128]
I have an RX-V677 and know it's not on the support list, but everything around it is.  Hoping it "just works" I made an attempt and am getting this error when adding the integration:

```
Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble
```

I was able to power the receiver off and on with the entities found from the basic integration so at least I know HA _can_ talk to the receiver.  

What logs/etc. would you like to see?  Thanks

**Comment by mvdwetering** [comment]
Hmm, that is kind of a generic error, so probably look in the Home Assistant logs. 

You can either go to Settings > System > Logs and click on the error there to get more info and paste here. Or just attach the homeassistant.log file here.

Just to be sure on what version of  Home Assistant and the integration ar you using?

**Comment by YAMLcase** [comment]
I just did a new docker pull last night:
```
Home Assistant 2023.1.7
Frontend 20230110.0 - latest
```

**Comment by YAMLcase** [comment]
logs showing no permissions for `/.local`.  This would be in the container with processes running under a specific UID.  Guess that was bound to catch up to me sooner or later.

```
2023-02-01 17:57:47.315 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package ynca==5.2.0: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
```

**Comment by YAMLcase** [comment]
I created the dir and made sure I had permissions, which looks like there was a pip install to that dir.  Now getting this error in UI:
```
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

and in stderr:
```
2023-02-01 18:01:41.129 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration yamaha_ynca: No module named 'ynca'
```

ynca is the only thing going in, is this the right location?

```
/.local
└── lib
    └── python3.10
        └── site-packages
            ├── ynca
            │   ├── __pycache__
            │   └── subunits
            │       └── __pycache__
            └── ynca-5.2.0.dist-info

```

**Comment by mvdwetering** [comment]
It seems that your Home Assistant has some issues downloading/installing python libraries. That is kind of "core" for HA and is something that should just work. 

It is unclear to me why HA is trying to install in `.local` (and I am not sure if that is in or outside the container). 

This seems to be more of an Home Assistant issue than specific to this integration as the integration is not even being installed. I have never seen anything like this and I don't really know Docker, so maybe ask/search around on the forums/discord to see if other people had similar experiences.

**Comment by YAMLcase** [comment]
ok that's fine. I'm ok with closing the issue

**Comment by mvdwetering** [comment]
As an FYI. If you can solve the package installation issue your receiver should work according to the user in #129
