### ISSUE TITLE
rx-v677

### ISSUE THREAD

**Issue by dguihal** [mvdwetering/yamaha_ynca#129]
**Describe the bug**
For some long time I add my  rx-v677 working properly

but since some releases (not sure since when) I got some connections errors on it from home assistant (although my device web ui is fully available)

I recently tried to uninstall/reinstall the integration (remove integration / remove hacs plugin / reinstall everything)

And now I'm not even able to configure it yet, 
![image](https://user-images.githubusercontent.com/4045744/217018454-4d86a828-9408-442a-a84e-1e09fe644b8a.png)

(nginx is my front end proxy)

I tried direct curl bypassing nginx, but it just hang forever.

I just can't find any meaningful logs on ha output
I only found
> :0:0 ResizeObserver loop completed with undelivered notifications.
> 16:48:38 – (ERREUR) components/system_log/__init__.py - message survenu pour la première fois à 15:31:40 et apparu 5 fois. 

But unsure it's related

**To Reproduce**
1. Try to setup a YNCA integration in HA
2. Timeout while trying to load configuration UI

**Expected behavior**
Have the YNCA configuration page showed

**Diagnostics**
If possible add diagnostics data from HA. The "Download diagnostics" option can be found in the vertical 3 dots menu (⋮) of the integration.

Please add the file itself (drag-and-drop in this box). Do not, copy-paste the contents here as it will make the issue unreadable

**Logging**
If there are errors in the Home Assistant logs please add them here.

**Home Assistant version information:**
 - Version 2023.2.2

**Additional context**

**Comment by mvdwetering** [comment]
Hmm.. that is not a lot to go on.  

Could you add the following to your `configuration.yaml` file to enable additional logging? (or extend the `logger:` section if it already exists with the 2 lines mentioning "ynca" ).

Then restart Home Assistant and try to add the integration again and post the Home Assistant logs.

```
logger:
  default: info
  logs:
    ynca: debug
    custom_components.yamaha_ynca: debug
```

**Comment by dguihal** [comment]
Thanks for the answer.

I did as you asked and for some reason it solved my issue ?????

Maybe the HA restart but I did it multiple time so I don't really get why this time it would have been better .....

Anyway it's working now

BTW you can add RX-V677 on your working model list, although quite old it's well supported by your integration, good job.
