### ISSUE TITLE
Change Ip

### ISSUE THREAD

**Issue by bootstrapbats** [mvdwetering/yamaha_ynca#159]
When pressing configure I like to be able to change IP adress for my receiver.

**Comment by mvdwetering** [comment]
Not sure what is the best way to build and test that, but will take a look at that.

**Comment by mvdwetering** [comment]
This is now possible with the v7.1.0 release.

The procedure is a bit clumsy, but doing it this way allows me reuse the existing configuration flow and avoid adding a lot of code to maintian and test.

> Q: How can I change the connection settings
> When the integration can not connect to the receiver (e.g. due to changed IP address) you can use the "Configure" button on the integration card. A dialog appears with a message that it can't connect. Press "Submit" in this dialog to mark the integration for reconfiguration. Home Assistant will now allow you to reconfigure the integration (reload of the page in the browser seems required to show the reconfigure card).
