### ISSUE TITLE
Support for RX-Vx800 over serial bridge

### ISSUE THREAD

**Issue by daza67** [mvdwetering/yamaha_ynca#16]
I recently came across this integration and was hoping to control an older RX-V3800 I use as a zone amplifier to extend my home audio system. I noticed the readme said the RX-V2600 was also supported which appears to be a slightly earlier vintage of receiver 
compared to what I am using. Links to both protocol docs, [RX-Vx600](https://us.v-cdn.net/6031006/uploads/vbulletin_attachments/9/7/2/244.pdf) , [RX-Vx800](https://www.avsforum.com/attachments/rx-vx800_rs232c_standard-pdf.17905/).

When I look at the RS232 protocol docs for the both they look extremely similar, communication needs to be opened in the same way, To quote the protocol docs "The Ready command is the first command to be sent to the RX-Vx600 at the start of communication. TOUT0 - 2 in the Ready Command sets communication timeout. RX-Vx600 sends a Configuration command (Model ID, software version, and setting data) to the host in reply to the Ready command."

From then after you basically send the ASCII string with a wrapper e.g. #STX07A1D#ETX encoded as hex 02 30 37 41 31 44 03 for an ON command as an example. I have all this working via a homebrew serial to TCP bridge based on tasmota. The hardware appears to function fine as I can fully control the receiver manually sending commands via the Hercules TCP client utility. 

![image](https://user-images.githubusercontent.com/35350624/186999764-54e6074a-caf3-4cca-ab6b-ed62f4c7c78b.png)

When I try and setup the receiver I'm using the PySerial URL method using this URL socket://192.168.222.222:8888. I can see the TCP handshake establish and HA appears to send some data however the receiver doesn't seem to respond. I have attached a wireshark trace of the traffic.
[ynca_rx-v3800_trace.zip](https://github.com/mvdwetering/yamaha_ynca/files/9436765/ynca_rx-v3800_trace.zip)

I'm more a network guy so I don't quite have the skillset to debug this further and I was hoping you could take a look.

Edit: I now think this protocol is not actually YNCA but an earlier protocol based on their IR commands.

**Comment by mvdwetering** [comment]
This protocol is unfortunately not YNCA. 

The assumption the RX-V2600 was supported is based on a note in one of the YNCA specs floating around the internet, but that info seems to be wrong, so I will remove the RX-V2600 it from the list.

Since adding other protocols is out of scope for this integration I am closing this issue.
