### ISSUE TITLE
Can't find my receiver anymore

### ISSUE THREAD

**Issue by Swiiney** [mvdwetering/yamaha_ynca#179]
**Describe the bug**
Integration was working but since today it doesn't connect to my receiver (RX-V475). Official application is working. 

**To Reproduce**
1. Go to reconfiguration
2. Enter ip address
3. Click on validate
4. Error "Failed to connect, check settings. " 

**Expected behavior**
Connect to the receiver

**Diagnostics**
Ping from my raspberry to the receiver is working
Ping from inside the HA container (docker) to the receiver is ok

Please add the file itself (drag-and-drop in this box). Do not, copy-paste the contents here as it will make the issue unreadable

**Logging**
If there are errors in the Home Assistant logs please add them here.
No logs...  But looking to complete if find any. 

**Home Assistant version information:**
 - Version 2023.6.1 

**Additional context**

**Comment by mvdwetering** [comment]
Make sure you have updated the integration to 7.3.0 it fixes unable to connect issue with Home Assistant 2023.6.x / Python 3.11

**Comment by Swiiney** [comment]
You are right. Working Now.
Sorry.
Thanks for your help
