### ISSUE TITLE
Addition of the HDMI OUT toggle within the integration

### ISSUE THREAD

**Issue by aiden21c** [mvdwetering/yamaha_ynca#184]
My Yamaha reciever (RX-V773) has the ability within the Yamaha AVR app to toggle the various HDMI outputs. It features two outputs which are both mirrored and attached to Zone 1 within the receiver. This gives me the ability to sometimes use my TV and sometimes use my projector depending on the situation.

I was wondering if it might be possible to add the ability to toggle these HDMI outputs within HA as can be done within the Yamaha AVR app. I've attached a screenshot of what the setting looks like in the app.

Im happy to help test and pull logs from the device if necessary as I understand not all receivers may have this function.
![Screenshot_20230615-214854_AV Controller](https://github.com/mvdwetering/yamaha_ynca/assets/49219164/6752f634-38c8-43b5-a4a5-297bd3b3265f)

**Comment by mvdwetering** [comment]
You are in luck :)

I recently started on that by a request in https://github.com/mvdwetering/yamaha_ynca/discussions/119

I was close to finished, but then there was an issue with the HA 2023.6.0 release which required some immeditate attention due to the connection issue. I will pick this up again soon.

(that is assuming your receiver uses the same commands as the TSR-700, but that is very likely it does)

**Comment by aiden21c** [comment]
That's awesome. Let me know if you'd like me to complete any testing on my unit once you've completed the feature and I'll keep and eye out on the upcoming release notes. Cheers!

**Comment by mvdwetering** [comment]
I just release 7.4.0 which added support for HDMIOUT toggles on TSR-700, I expect that your receiver uses the same commands and should therefore also work.

**Comment by aiden21c** [comment]
That's awesome. Thank you very much. I'm still on HA 2023.5.3.3 so once my provider TrueCharts pushes the update to 2023.6.0 I'll be able to update the integration and test it. I'll let you know if there are any issues. Thanks for your work!

**Comment by aiden21c** [comment]
I just updated and that seems to have worked a treat. Thank you very much for your hard work!

**Comment by mvdwetering** [comment]
Good to hear it works.

I will be closing the issue as it has been implemented
