### ISSUE TITLE
RX-V679

### ISSUE THREAD

**Issue by kowost** [mvdwetering/yamaha_ynca#227]
Unfortunately I can not connect to my receiver. Attached my configuration/log. Connection would be done via network.
Any help appreciated.

Config :

- HA : 2023.12.4
- YNCQ : 7.5.1
- Receiver-Firmware 2.86
- "Network Standby" is "On"

Log :
2024-01-02 01:18:05.170 DEBUG (Thread-7) [ynca.connection] Connected
2024-01-02 01:18:05.170 DEBUG (Thread-8 (_send_handler)) [ynca.connection] Send - @SYS:MODELNAME=?
2024-01-02 01:18:05.191 DEBUG (Thread-7) [ynca.connection] Connection closed/lost read failed: [Errno 104] Connection reset by peer

**Comment by mvdwetering** [comment]
I have seen this error when there is already something else connected to the receiver using the YNCA protocol.
There is a limitation on the receiver that it can only handle 1 connection for this protocol, the second connection attempt will get disconnected.

Could it be that there is some other home automation system (or something else) already connected?

**Comment by kowost** [comment]
Absolutely right. My iobroker was blocking the connection. After stopping the adapter in iobroker I was able to connect to my RX-V679. 
So I now can confirm that **RX-V679 also works**.

Many thanks!

**Comment by mvdwetering** [comment]
Cool, nice to hear it works now. Adding the RX-V679 to the readme now.

The sad part is that I actually have a hint about only-one-connection-allowed in the connection error message but I messed up and some texts got swtiched around so you got the generic "something is wrong" error. Will fix that shortly.
