### ISSUE TITLE
Module Could Not Be Loaded

### ISSUE THREAD

**Issue by aiden21c** [mvdwetering/yamaha_ynca#250]
**Describe the bug**
After an automatic update (I believe from  v17.2.30 to v2024.2.1 provided by Truecharts) the module can no longer be loaded by Home Assistant.

**To Reproduce**
1. Update HA instance to v2024.2.1
2. Module cannot be loaded

**Expected behavior**
Module loads as per normal and the integration works as it did prior.

**Diagnostics**
If possible add diagnostics data from HA. The "Download diagnostics" option can be found in the vertical 3 dots menu (⋮) of the integration.
![image](https://github.com/mvdwetering/yamaha_ynca/assets/49219164/1596cc7c-67d4-4567-aec3-a2c972749b8c)

Please add the file itself (drag-and-drop in this box). Do not, copy-paste the contents here as it will make the issue unreadable

**Logging**
If there are errors in the Home Assistant logs please add them here.
[home-assistant_2024-02-15T11-17-39.312Z.log](https://github.com/mvdwetering/yamaha_ynca/files/14296017/home-assistant_2024-02-15T11-17-39.312Z.log)

**Environment**
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

- Home Assistant Core version: v2024.2.1
- Home Assistant operating environment (OS/Container/Supervised/Core): Docker container on Truenas Scale via Truecharts
- Integration version: v7.5.1
- Last working version (if known): v17.2.30

**Additional context**
I am attempting to roll back to the previous release (Truecharts [home-assistant-23.0.14](https://github.com/truecharts/charts/compare/home-assistant-23.0.13...home-assistant-23.0.14)) and will update if i can confirm functionality.

**Comment by mvdwetering** [comment]
It looks like Home Assistant could not download the package for some reason. I don't think there is anything I can do about that.
The bravia_psk integration seems to have a similar issue on line 87 in your log.

There are a lot of what seem to be network errors in your logs. Could it be that there was a network issue at that time?
