### ISSUE TITLE
Tuner preset is not set if input was other than Tuner

### ISSUE THREAD

**Issue by tramperb** [mvdwetering/yamaha_ynca#271]
If the A/V receiver (AVR) is set to an input other than Tuner (eg HDMI1), running the media_player.play_media service to set a tuner preset does not set the preset.  It will change the input to Tuner but leave the preset unchanged.  Running the service a 2nd time sets the correct preset.

To Reproduce
1. set AVR input to Tuner and note the current preset (eg 1)
2. change AVR input to other than Tuner (eg HDMI1)
3. run media_player.play_media service with a Content ID that sets a different preset (eg tun:preset:4)
4. result : the AVR input is changed to Tuner but the preset remains unchanged (in this example, 1)
5 a. the expected result is that the AVR input changes to Tuner _and_ the preset is changed (in this example, to 4)
5 b. if the service is run a 2nd time, the preset is correctly set (in this example, to 4)

Environment
HA 2024.3.3 Container, Yamaha YNCA v7.7.0, AVR RX-A740

**Comment by mvdwetering** [comment]
Hmm... it indeed does not switch also on my receiver.

I will need to figure out what is the magic to get it to work. Just sending the preset command twice does not seem to help :/
I guess some kind of delay might be needed, but not sure what would be a reasonable value for that.

**Comment by tramperb** [comment]
Yes, a delay may be needed.  A quick (very rough) test of the time it takes for my Yamaha app to update the input from HDMI1 to Tuner is < 2sec.  So, perhaps start with 1.5sec and reduce ??
(I can follow the logic of media_player.py but couldn't write it :))

**Comment by mvdwetering** [comment]
I ended up adding a delay of 1 second which works on my receiver, 0.5 seconds did not work. The change is in v7.7.1

Could you give it a try?

**Comment by tramperb** [comment]
Thanks - would you recommend changing to a HACS install?

**Comment by tramperb** [comment]
Thanks - will do later today.

**Comment by tramperb** [comment]
Sorry, hit the wrong button (unintended close :)

**Comment by tramperb** [comment]
Unexpected window to try v7.7.1.  Applied & tested (twice) and yes, working well.  1sec seems to be a good choice - fixes the issue but doesn't seem like a slow response to the button push.
Thanks for the quick fix.
