### ISSUE TITLE
Unknown value 'TV' in Input

### ISSUE THREAD

**Issue by joos81** [mvdwetering/yamaha_ynca#293]
Describe the bug
Homeassistant shows Log Warning (see Warning Section) under normal operation. I do not know if and how I triggered the warning or if it's just because the integration is used.

Also: The mediaplayer doesn't offer TV as a input

To Reproduce
Have a RX-A2A

Expected behavior
No Warning

Diagnostics

Logging

Logger: ynca.enums
Bron: /usr/local/lib/python3.12/site-packages/ynca/enums.py:216
Eerst voorgekomen: 13:32:38 (1 gebeurtenissen)
Laatst gelogd: 13:32:38

Unknown value 'TV' in Input

Environment
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

Home Assistant Core version: 2024.6.4
Home Assistant operating environment (OS/Container/Supervised/Core): Supervised VM
Integration version: v7.8.0
Last working version (if known): never?
Additional context

**Comment by mvdwetering** [comment]
I suspect this related to the "input" for the eARC/ARC signal from the TV.

If I understand correctly it allows you to have the sound from your TV coming back into the HDMI-OUT of the receiver. It would for example allow you to watch Netflix with the App on the TV and still have the sound on the receiver.

Could you attach (drag-and-drop the file in the comment textbox) the diagnostics. Preferrable soon-ish after this happens, but if hard to do send it anyways. It allows me to see the messages received by the integration, so I can see exactly what is going on.

Diagnostics file can be downloaded from the integration page on the vertical 3 dot menu.
![image](https://github.com/mvdwetering/yamaha_ynca/assets/732514/62bfd816-9a8d-4615-a520-e476b3089062)

**Comment by joos81** [comment]
[config_entry-yamaha_ynca-db01c5529ae5b7c33b667e5e1084c23d.json](https://github.com/user-attachments/files/16019212/config_entry-yamaha_ynca-db01c5529ae5b7c33b667e5e1084c23d.json)
I can easily reproduce the warning by turning on the receiver when the last source was TV.
If the solution is the same as adding the previous AUDIO5 input, I took the liberty to already create a PR (I hope I did it in the right way as it is my first :-) )

**Comment by mvdwetering** [comment]
PR seems mostly fine. I left 1 comment on it. 
After fixing that probably the tests will also be fine.
