### ISSUE TITLE
Add SurroundDecoder modes as soundmodes

### ISSUE THREAD

**Issue by mvdwetering** [mvdwetering/yamaha_ynca#31]
**Is your feature request related to a problem? Please describe.**

Yamaha receivers offer "Surround Decoder" modes like "Dolby PLII Movie" or "DTS NEO:6 Cinema", but these are not available in the integration.

**Describe the solution you'd like**
It would be nice to have those SurroundDeocder modes available as soundmodes

**Describe alternatives you've considered**
Don't use the modes through Home Assistant

**Additional context**

Notes to self:
These modes are set through "2CHDECODER" in combination with the SOUNDPRG set to "Surround Decoder", so these modes are kind of a subselection it it seems.

The "Dolby PLIIx" variants seem to be silently translated to the non "x"  variants by my receiver. Might be related to the "x" being for better backchannels in 7.1 which I don't have setup (only 5.1, but receiver could do 7.1)? Would need to test on a 7.1 setup to see what happens then.
This makes supporting these options weird as setting one options returns another.

Would modern receivers support the Dolby Pro Logic IIz (adds 2 front height channels)?

For surround decoder there also extended settings which may (or may not) interact with the SurroundDecoder. These are on the "EXSURDECODER" function which seems to vary between Off, Auto and EX/ES.

**Comment by AnthonyBe** [comment]
I think this might be related to an error I came here to report.

I get the following in my HA log on start-up:
`WARNING (Thread-2) [ynca.enums] Unknown value 'DTS Neural:X' in TwoChDecoder`

I have a Yamaha RX-A1060 receiver.

**Comment by mvdwetering** [comment]
Surround decoders have not been really supported yet in the Home Assistant integration. This was mostly a reminder for me to expose it at some point. However the protocol handling _does_ already try to read those values, but it turns out that the list of decoders completely changed in some later models, which results in the warning you are seeing.

For now you can ignore the warning, it should not have negative effects.

That being said, could you cycle through the available SurroundDecoder options on your receiver and then report back with the diagnostics file (you can get it from the 3 dot menu on the device page or integration card). It logs the most recent messages received and will allow me to learn about all possible values so I can add them to the list and get rid of the warning.

**Comment by mvdwetering** [comment]
Surround Decoder selection is implemented in v6.1.0 for receivers that support the Dolby Prologic and DTS Neo versions. 

@AnthonyBe I added the 'DTS Neural:X` as a known value so the warning should not show up anymore. I will close this issue as the original intended implementation is done. If you want support for the `DTS Neural:X`  and other modern modes please open a new issue.
