### ISSUE TITLE
RX-V500D load failed

### ISSUE THREAD

**Issue by OStrama** [mvdwetering/yamaha_ynca#315]
Error setting up RX-V500D

At start of Home Assistant the following log appears:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.yamaha_ynca
Quelle: custom_components/yamaha_ynca/__init__.py:148
Integration: Yamaha (YNCA) (Dokumentation, Probleme)
Erstmals aufgetreten: 22:21:40 (4 Vorkommnisse)
Zuletzt protokolliert: 22:22:53

Unexpected exception during initialization of RX-V500D
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/yamaha_ynca/__init__.py", line 148, in initialize_ynca
    ynca_receiver.initialize()
  File "/srv/homeassistant/lib/python3.12/site-packages/ynca/api.py", line 192, in initialize
    self._initialize_available_subunits(connection)
  File "/srv/homeassistant/lib/python3.12/site-packages/ynca/api.py", line 118, in _initialize_available_subunits
    system = System(connection)
             ^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/ynca/subunit.py", line 59, in __init__
    attribute = getattr(self.__class__, attribute_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: __provides__. Did you mean: '__providedBy__'?

- Home Assistant Core version:  2024.7.4
- Home Assistant operating environment (OS/Container/Supervised/Core):  Core on P5
- Integration version: 7.10.1 
- Last working version (if known):  unknown used it last time approx. 1 Month ago.

Please contact me if you need more info, thanks in advance for your help!

**Comment by mvdwetering** [comment]
Just released 7.10.1 which should fix this issue.

**Comment by OStrama** [comment]
Interesting. I do not have installed so much integrations. How can I find out which of them uses zope interfaces?
I’ll test the new version tomorrow evening and let you know if it works on my installation.

**Comment by OStrama** [comment]
Installed the new version some minutes ago. Works perfect again! Thank you!
