### ISSUE TITLE
RX-V1067 - Pure Direct feature not detected  / creating a switch

### ISSUE THREAD

**Issue by DeviousAl** [mvdwetering/yamaha_ynca#331]
This amp has PureDirect feature - but it is a system wide feature like AdaptiveDRC and Ceinema DSP3D mode - but it's not pulling in the switch config / button option for this feature on the amp.

Not sure if it's because checking against zone or not (my coding skills are limited!). However I know this Amp has it as I see it in the AV Controller app by Yamaha and use it for Karaoke mode.

**Comment by mvdwetering** [comment]
Can you toggle the PureDirect feature on your receiver and then download and attach the diagnostics file?
It will allow me to see the recent commands from the receiver and let me debug it.

You can get the diagnostics file by opening the ⋮ menu and select download diagnostics. 
![image](https://github.com/user-attachments/assets/7ae65278-9de9-4d8e-9c4c-b2d3f0bb54bf)

**Comment by DeviousAl** [comment]
Sure, thanks for taking a look!

[config_entry-yamaha_ynca-01J9GGKZFCFDANDXWR9H8SHRHT (1).json](https://github.com/user-attachments/files/17269225/config_entry-yamaha_ynca-01J9GGKZFCFDANDXWR9H8SHRHT.1.json)

**Comment by DeviousAl** [comment]
It seems to be seeing the commands:

`
        "Received: @SYS:MODELNAME=RX-V1067",
        "Received: @MAIN:PUREDIRMODE=Off",
        "Received: @MAIN:STRAIGHT=On",
        "Received: @MAIN:PUREDIRMODE=On",
        "Received: @MAIN:STRAIGHT=On",
`

Yet I don't see the switch / config option under the reciever being created:

![image](https://github.com/user-attachments/assets/579582ea-0b7e-4d7b-b63e-5232ef83793e)

**Comment by mvdwetering** [comment]
Weird, the commands look fine at first look. 

Hmm, but it only shows in the diagnostics "history" when you toggled it and not during "initialization". The `@MAIN:PUREDIRMODE` status was expected to come back as part of the request for the `@MAIN:BASIC=?` parameters. I guess it is not standardized to be included in that on all models :/ 

Looks like I will have to request `PUREDIRMODE` explicitly during startup instead of relying on it to be part of the `BASIC` response.

**Comment by mvdwetering** [comment]
I just released which fixes the missing Pure Direct switch. 
At least I am pretty confident it will fix it 😊

**Comment by DeviousAl** [comment]
Thank you! First time having to go through this. Is it a redownload from HACS and reload integration?

Cheers,

Alex

**Comment by mvdwetering** [comment]
HACS will inform you about the update eventually (I think it checks once a day).
You can force it to update the info by using the : menu in the HACS integration menu and selecting "Update information"
I think it then shows up with the other available updates in Home Assistant.
Then install the update from the update entity.
After that HACS will create a repair with a reminder to restart Home Assistant.

(this is from the top of my head, not 100% sure with the recent changes in HACS 2.0)

**Comment by DeviousAl** [comment]
I can con confirm this now shows (updated in hacs then rebooted). Thank you!

What's the best way to toggle the feature via automation / dashboard - send the YNCA raw command? @MAIN:PUREDIRMODE=On

or is there some other elegant way I'm missing - as it's not exposed as a variable under the mediaplayer?

Cheers!

**Comment by DeviousAl** [comment]
Ah i see it exposes a switch entity that can be used!

**Comment by mvdwetering** [comment]
Yup, it adds a switch. The YNCA Raw command is only there for debugging purposes.

For completeness an image in case someone runs into this in the future.

![image](https://github.com/user-attachments/assets/1edec4bc-fd90-4d10-a4b6-2218c1abf474)

I will close this issue as it has been implemented and verified.
