### ISSUE TITLE
Support for Yamaha RX-V3900

### ISSUE THREAD

**Issue by lennartjung** [mvdwetering/yamaha_ynca#42]
**Is your feature request related to a problem? Please describe.**
Unfortunately my Yamaha RX-V3900 Receiver does not seem to be supported by this integration. 

**Describe the solution you'd like**
Control input and volume settings via HA

**Describe alternatives you've considered**
tried using different ports other than 50000 (default), without any luck.

PORT      STATE SERVICE
80/tcp    open  http
49153/tcp open  unknown
65432/tcp open  unknown
65434/tcp open  unknown

Using the webinterface is a working alternative but not as nice as using HA directly.

**Additional context**
Given the fact that the receiver is providing a webserver with no authentication there should be a way of using HTTP post methods to press the "buttons" via HA.
In case additional information is required, please contact me, I am more than happy to help/support with webpage sourcecode a.s.o.

**Comment by mvdwetering** [comment]
This receiver uses a different protocol (YNC / YRSC) as what is supported by this integration (YNCA). 

I will not be adding support for other protocols to this integration as it will make it too complex to maintain. Unfortunately that  means that this integration will not be able to communicate with this model receiver.

As alternative I think the Yamaha integation that comes with Home Assistant uses that protocol so you might try to use that integration instead. For documentation on that see: https://www.home-assistant.io/integrations/yamaha/

If that does not work you might be able to "manually" send commands from Home Assistant with "RESTful Command" or other integrations that allow sending HTTP requests. I never really used those myself. You should probably ask on the Homae Assistant forums to get help on those if needed.
