### ISSUE TITLE
RX-V2065

### ISSUE THREAD

**Issue by Migaddo** [mvdwetering/yamaha_ynca#52]
Hi Would it be possible to get the Yamaha RX-V2065 working with this integration?
Trying to connect  through IP Address, however it states a message 'Failed to connect, check settings.'

The link towards my Desc.XML file is 
http://[192.168.2.132/YamahaRemoteControl/UnitDesc.xml](http://192.168.2.132/YamahaRemoteControl/UnitDesc.xml)

**Comment by mvdwetering** [comment]
I am closing this issue as I think there is nothing I can do on my side
