### ISSUE TITLE
Receiver DNS address support

### ISSUE THREAD

**Issue by lucamarien** [mvdwetering/yamaha_ynca#70]
Hi,

is it possible to add DNS Support to the Receiver IP address field?

I like to manage my smart devices in a dynamic manner and assume I am not the only one!?

Really great intergration you got going.

**Comment by mvdwetering** [comment]
Ah, Github autocloses the ticket also when mentioning it in a pullrequest :) 

Anyway, hostnames should work now with v5.1.0. I was only able to test it with a change to the hosts file, but as long as your Home Assistant server can resolve the address it should work.

**Comment by lucamarien** [comment]
Wow, that was fast.
Works now, thank you.
